### ISSUE TITLE
Population data sources

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/NHSRpopulation#1]
There is an estimated population by age and LSOA `https://www.ons.gov.uk/file?uri=%2fpeoplepopulationandcommunity%2fpopulationandmigration%2fpopulationestimates%2fdatasets%2flowersuperoutputareamidyearpopulationestimates%2fmid2019sape22dt2/sape22dt2mid2019lsoasyoaestimatesunformatted.zip` but there are also data sources like GP registered population that may be useful in this package. I'll edit with the url when I find it.

**Comment by milanwiedemann** [comment]
I've added the main population estimates from LSOA and IMD scores. There are also population estimates in the original source of the IMD file that I didn't include because they seem to be from 2015. Maybe something we could look into at some point in the future but I'm closing this for now
