### ISSUE TITLE
Name Change from LSOApop?

### ISSUE THREAD

**Issue by BlenderMcCoy** [nhs-r-community/NHSRpopulation#19]
![image](https://user-images.githubusercontent.com/801831/213666554-2898e398-7ff1-4dce-9d37-23d3742a2639.png)
link here to LSOApop doesn't work

Wondering if the repository was renamed to NHSRpopulation and this update just didn't flow through?

**Comment by ChrisBeeley** [comment]
Good spot, fixed it, thanks!

**Comment by BlenderMcCoy** [comment]
Good God that was quick!

...also my first raised GitHub issue

Cheers for this repository btw!  It's a great step-in for me trying to learn more about R!
________________________________

**Comment by ChrisBeeley** [comment]
Thank you for raising an issue!

If you're keen to learn can I please recommend demo's and how to's https://github.com/nhs-r-community/demos-and-how-tos.

Chock full of useful code, and always happy to receive submissions so if you've done anything interesting with R please consider making a pull request :pray: :relaxed:
